### ISSUE TITLE
Same Size and binary when using Zain

### ISSUE THREAD

**Issue by hassanmhd** [asim-jaweesh/Packet-Injection-in-Sudan-Analysis#1]
Hi Asim, 
you're doing a great effort in investigating what's happening, and i'm really interested in seeing what's happening too!

I tried to replicate your results for the antivirus file.. i used the same link as yours.
I got the same file in both cases(with and without vpn)

### below is the file size for both : 

![screen shot 2018-03-13 at 4 27 00 pm](https://user-images.githubusercontent.com/5237304/37347871-7fa66f2e-26db-11e8-84e0-1084fcfa59f8.png)

as you can see, the size is 5546232 (exactly the same as your original untampered file).

### and here is the binary difference : ( No difference found)  : 

![screen shot 2018-03-13 at 4 23 35 pm](https://user-images.githubusercontent.com/5237304/37347640-f7538c24-26da-11e8-9698-296b7a2b7478.png)

I'm using Zain 4G Data SIM card.. maybe Zain isn't included in this?

## Note
**test.exe** => file downloaded with VPN
**text_tampered.exe** => file downloaded without VPN

**Comment by jaweesh** [comment]
then maybe 4G is not affected, yet. but I have an old download from Zain 3G network with an IP belonging to them intercepting the package the same way 

information is being added to the repo.

![whatsapp-evill-download](https://user-images.githubusercontent.com/4925223/37357093-3480635a-26f0-11e8-9747-bda791512b4b.PNG)
